-- Event analytics pipeline tables.
-- NOTE: Existing `analytics` and `listing_analytics` tables are intentionally untouched.

create table if not exists analytics_sessions (
  id uuid primary key default gen_random_uuid(),
  listing_id bigint not null references listings(id) on delete cascade,
  visitor_id text,
  user_id uuid,
  session_source text,
  session_medium text,
  user_agent text,
  ip_hash text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references analytics_sessions(id) on delete cascade,
  listing_id bigint not null references listings(id) on delete cascade,
  event_name text not null,
  event_value numeric,
  occurred_at timestamptz not null default now(),
  page_path text,
  referrer text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Optional daily rollups.
create table if not exists analytics_listing_daily (
  day date not null,
  listing_id bigint not null references listings(id) on delete cascade,
  event_name text not null,
  event_count bigint not null default 0,
  unique_sessions bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (day, listing_id, event_name)
);

create table if not exists analytics_tier_daily (
  day date not null,
  tier text not null,
  event_name text not null,
  event_count bigint not null default 0,
  unique_sessions bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (day, tier, event_name)
);

-- Reconcile pre-existing tables so index/policy creation remains safe on re-runs.
alter table if exists analytics_sessions
  add column if not exists listing_id bigint references listings(id) on delete cascade,
  add column if not exists visitor_id text,
  add column if not exists user_id uuid,
  add column if not exists session_source text,
  add column if not exists session_medium text,
  add column if not exists user_agent text,
  add column if not exists ip_hash text,
  add column if not exists started_at timestamptz not null default now(),
  add column if not exists ended_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table if exists analytics_events
  add column if not exists session_id uuid references analytics_sessions(id) on delete cascade,
  add column if not exists listing_id bigint references listings(id) on delete cascade,
  add column if not exists event_name text,
  add column if not exists event_value numeric,
  add column if not exists occurred_at timestamptz not null default now(),
  add column if not exists page_path text,
  add column if not exists referrer text,
  add column if not exists properties jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

alter table if exists analytics_listing_daily
  add column if not exists day date,
  add column if not exists listing_id bigint references listings(id) on delete cascade,
  add column if not exists event_name text,
  add column if not exists event_count bigint not null default 0,
  add column if not exists unique_sessions bigint not null default 0,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists analytics_tier_daily
  add column if not exists day date,
  add column if not exists tier text,
  add column if not exists event_name text,
  add column if not exists event_count bigint not null default 0,
  add column if not exists unique_sessions bigint not null default 0,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- Indexes for safe query performance.
create index if not exists analytics_events_occurred_at_idx
  on analytics_events (occurred_at desc);

create index if not exists analytics_events_listing_time_idx
  on analytics_events (listing_id, occurred_at desc);

create index if not exists analytics_events_session_time_idx
  on analytics_events (session_id, occurred_at desc);

create index if not exists analytics_events_event_name_time_idx
  on analytics_events (event_name, occurred_at desc);

-- Baseline auth helpers for RLS.
create or replace function analytics_is_admin()
returns boolean
language sql
stable
as $$
  select
    coalesce(auth.jwt() ->> 'role', '') in ('service_role', 'admin')
    or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin');
$$;

create or replace function analytics_is_approved_path()
returns boolean
language sql
stable
as $$
  select
    analytics_is_admin()
    or coalesce(auth.jwt() ->> 'path', '') in ('/listings', '/listing', '/listing.html');
$$;

create or replace function analytics_is_listing_owner(target_listing_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from business_owners bo
    where bo.listing_id = target_listing_id
      and bo.owner_user_id::text = auth.uid()::text
  );
$$;

alter table analytics_sessions enable row level security;
alter table analytics_events enable row level security;
alter table analytics_listing_daily enable row level security;
alter table analytics_tier_daily enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_sessions' and policyname = 'Insert analytics sessions from approved path'
  ) then
    create policy "Insert analytics sessions from approved path"
      on analytics_sessions
      for insert
      to anon, authenticated
      with check (analytics_is_approved_path());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_events' and policyname = 'Insert analytics events from approved path'
  ) then
    create policy "Insert analytics events from approved path"
      on analytics_events
      for insert
      to anon, authenticated
      with check (analytics_is_approved_path());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_sessions' and policyname = 'Admins can read analytics sessions'
  ) then
    create policy "Admins can read analytics sessions"
      on analytics_sessions
      for select
      to authenticated
      using (analytics_is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_events' and policyname = 'Admins can read analytics events'
  ) then
    create policy "Admins can read analytics events"
      on analytics_events
      for select
      to authenticated
      using (analytics_is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_sessions' and policyname = 'Business owners can read their analytics sessions'
  ) then
    create policy "Business owners can read their analytics sessions"
      on analytics_sessions
      for select
      to authenticated
      using (analytics_is_listing_owner(listing_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_events' and policyname = 'Business owners can read their analytics events'
  ) then
    create policy "Business owners can read their analytics events"
      on analytics_events
      for select
      to authenticated
      using (analytics_is_listing_owner(listing_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_listing_daily' and policyname = 'Admins can read listing daily rollups'
  ) then
    create policy "Admins can read listing daily rollups"
      on analytics_listing_daily
      for select
      to authenticated
      using (analytics_is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_listing_daily' and policyname = 'Business owners can read listing daily rollups'
  ) then
    create policy "Business owners can read listing daily rollups"
      on analytics_listing_daily
      for select
      to authenticated
      using (analytics_is_listing_owner(listing_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'analytics_tier_daily' and policyname = 'Admins can read tier daily rollups'
  ) then
    create policy "Admins can read tier daily rollups"
      on analytics_tier_daily
      for select
      to authenticated
      using (analytics_is_admin());
  end if;
end
$$;

-- Rollback (drop new objects only):
-- drop table if exists analytics_tier_daily;
-- drop table if exists analytics_listing_daily;
-- drop table if exists analytics_events;
-- drop table if exists analytics_sessions;
-- drop function if exists analytics_is_listing_owner(bigint);
-- drop function if exists analytics_is_approved_path();
-- drop function if exists analytics_is_admin();
