-- Analytics migration plan: listing_analytics -> analytics_events
-- Executes tasks:
-- 1) Backfill old listing_analytics into analytics_events
-- 2) Produce 7/30 day old-vs-new count comparison
-- 3) Disable dual-write and old client direct inserts
-- 4) Keep legacy table read-only during observation window

begin;

create table if not exists analytics_events (
    id bigint generated by default as identity primary key,
    listing_id text not null,
    action text not null,
    platform text,
    "timestamp" timestamptz not null default now(),
    user_agent text,
    source text not null default 'new_client',
    legacy_event_id bigint unique,
    inserted_at timestamptz not null default now()
);

create index if not exists analytics_events_listing_id_idx
    on analytics_events (listing_id);

create index if not exists analytics_events_timestamp_idx
    on analytics_events ("timestamp" desc);

create index if not exists analytics_events_action_idx
    on analytics_events (action);

alter table analytics_events enable row level security;

-- Remove legacy write policy if present; anon clients should not insert directly.
do $$
begin
  if exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = 'listing_analytics'
        and policyname = 'Allow public analytics tracking'
  ) then
    drop policy "Allow public analytics tracking" on listing_analytics;
  end if;
end $$;

-- RPC used by clients so direct table writes can remain disabled.
create or replace function track_analytics_event(
    p_listing_id text,
    p_action text,
    p_platform text default null,
    p_timestamp timestamptz default now(),
    p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into analytics_events (
        listing_id,
        action,
        platform,
        "timestamp",
        user_agent,
        source
    ) values (
        p_listing_id,
        p_action,
        p_platform,
        coalesce(p_timestamp, now()),
        p_user_agent,
        'rpc'
    );
end;
$$;

revoke all on function track_analytics_event(text, text, text, timestamptz, text) from public;
grant execute on function track_analytics_event(text, text, text, timestamptz, text) to anon, authenticated;

-- Observation period: keep legacy readable, block all writes.
create or replace function block_listing_analytics_writes()
returns trigger
language plpgsql
as $$
begin
    raise exception 'listing_analytics is read-only during analytics_events migration';
end;
$$;

drop trigger if exists listing_analytics_read_only on listing_analytics;
create trigger listing_analytics_read_only
before insert or update or delete on listing_analytics
for each statement
execute function block_listing_analytics_writes();

-- Backfill historical events. Uses legacy_event_id for idempotency.
insert into analytics_events (
    listing_id,
    action,
    platform,
    "timestamp",
    user_agent,
    source,
    legacy_event_id
)
select
    la.listing_id,
    la.action,
    la.platform,
    coalesce(la."timestamp", now()),
    la.user_agent,
    'backfill',
    la.id
from listing_analytics la
on conflict (legacy_event_id) do nothing;

commit;

-- Task 2: key metric parity report for fixed windows (7d/30d).
with windows as (
    select '7d'::text as window_name, now() - interval '7 days' as from_ts
    union all
    select '30d'::text as window_name, now() - interval '30 days' as from_ts
), metrics as (
    select unnest(array['view','call','website','directions','share','video_play'])::text as action
), old_counts as (
    select
        w.window_name,
        la.action,
        count(*)::bigint as cnt
    from windows w
    join listing_analytics la on la."timestamp" >= w.from_ts
    group by 1, 2
), new_counts as (
    select
        w.window_name,
        ae.action,
        count(*)::bigint as cnt
    from windows w
    join analytics_events ae on ae."timestamp" >= w.from_ts
    group by 1, 2
)
select
    w.window_name,
    m.action,
    coalesce(o.cnt, 0) as old_count,
    coalesce(n.cnt, 0) as new_count,
    coalesce(n.cnt, 0) - coalesce(o.cnt, 0) as delta
from windows w
cross join metrics m
left join old_counts o on o.window_name = w.window_name and o.action = m.action
left join new_counts n on n.window_name = w.window_name and n.action = m.action
order by case w.window_name when '7d' then 1 else 2 end, m.action;
