-- Stores business-submitted listing requests from /submit.html
CREATE TABLE IF NOT EXISTS listing_requests (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    business_name text not null,
    slug text,
    tagline text not null,
    description text not null,
    category text not null,
    subcategories text[] not null default '{}',
    primary_subcategory text,
    is_chain boolean not null default false,
    chain_name text,
    chain_id text,
    address text,
    city text,
    state text,
    zip_code text,
    country text default 'USA',
    phone text,
    email text,
    website text,
    logo text,
    photos text[] default '{}',
    video text,
    hours jsonb default '{}'::jsonb,
    social_media jsonb default '{}'::jsonb,
    reviews jsonb default '{}'::jsonb,
    additional_info jsonb default '[]'::jsonb,
    custom_ctas jsonb default '[]'::jsonb,
    owner_name text,
    owner_title text,
    from_greece text,
    owner_email text,
    owner_phone text
);

create or replace function set_listing_requests_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists listing_requests_updated_at on listing_requests;
create trigger listing_requests_updated_at
before update on listing_requests
for each row execute function set_listing_requests_updated_at();
