-- Stores business-submitted listing requests from /submit.html
create table if not exists listing_requests (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    business_name text not null,
    tagline text not null,
    description text not null,
    category text not null,
    subcategories text[] not null default '{}',
    primary_subcategory text,
    address text,
    city text,
    state text,
    zip_code text,
    country text default 'USA',
    phone text,
    email text,
    website text,
    logo text,
    photos text[] default '{}',
    video text,
    hours jsonb default '{}'::jsonb,
    social_media jsonb default '{}'::jsonb,
    reviews jsonb default '{}'::jsonb,
    additional_info jsonb default '[]'::jsonb,
    custom_ctas jsonb default '[]'::jsonb,
    owner_name text,
    owner_title text,
    from_greece text,
    owner_email text,
    owner_phone text,
    owner_name_title_visible boolean not null default true,
    owner_email_visible boolean not null default false,
    owner_phone_visible boolean not null default false,
    owner_contacts jsonb default '[]'::jsonb
);

alter table if exists listing_requests
  add column if not exists owner_name_title_visible boolean not null default true,
  add column if not exists owner_email_visible boolean not null default false,
  add column if not exists owner_phone_visible boolean not null default false,
  add column if not exists owner_contacts jsonb default '[]'::jsonb;

create or replace function set_listing_requests_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists listing_requests_updated_at on listing_requests;
create trigger listing_requests_updated_at
before update on listing_requests
for each row execute function set_listing_requests_updated_at();

alter table listing_requests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'listing_requests' and policyname = 'Allow public submit listing requests'
  ) then
    create policy "Allow public submit listing requests"
      on listing_requests
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

alter table if exists listing_requests
  alter column owner_name_title_visible set default true,
  alter column owner_email_visible set default false,
  alter column owner_phone_visible set default false;
