-- Stores business-submitted listing requests from /submit-listing.html
create table if not exists public.listing_requests (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    business_name text not null,
    tagline text not null,
    description text not null,
    category text not null,
    subcategories text[] not null default '{}',
    primary_subcategory text,
    address text,
    city text,
    state text,
    zip_code text,
    country text default 'USA',
    phone text,
    email text,
    website text,
    logo text,
    photos text[] default '{}',
    video text,
    hours jsonb default '{}'::jsonb,
    social_media jsonb default '{}'::jsonb,
    reviews jsonb default '{}'::jsonb,
    additional_info jsonb default '[]'::jsonb,
    custom_ctas jsonb default '[]'::jsonb,
    owner_name text,
    owner_title text,
    from_greece text,
    owner_email text,
    owner_phone text,
    owner_name_title_visible boolean not null default true,
    owner_email_visible boolean not null default false,
    owner_phone_visible boolean not null default false,
    owner_contacts jsonb default '[]'::jsonb
);

alter table if exists public.listing_requests
  add column if not exists owner_name_title_visible boolean not null default true,
  add column if not exists owner_email_visible boolean not null default false,
  add column if not exists owner_phone_visible boolean not null default false,
  add column if not exists owner_contacts jsonb default '[]'::jsonb;

create or replace function public.set_listing_requests_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists listing_requests_updated_at on public.listing_requests;
create trigger listing_requests_updated_at
before update on public.listing_requests
for each row execute function public.set_listing_requests_updated_at();

alter table public.listing_requests enable row level security;

drop policy if exists "Allow public submit listing requests" on public.listing_requests;
drop policy if exists "Allow admin read listing requests" on public.listing_requests;
drop policy if exists "Allow admin update listing requests" on public.listing_requests;
drop policy if exists "Allow admin delete listing requests" on public.listing_requests;

create policy tgd_requests_public_insert
  on public.listing_requests
  for insert
  to anon, authenticated
  with check (
    nullif(trim(coalesce(business_name, '')), '') is not null
    and nullif(trim(coalesce(tagline, '')), '') is not null
    and nullif(trim(coalesce(description, '')), '') is not null
    and nullif(trim(coalesce(category, '')), '') is not null
  );

create policy tgd_requests_admin_select
  on public.listing_requests
  for select
  to authenticated
  using (
    coalesce((select auth.jwt()) ->> 'role', '') in ('admin', 'service_role')
    or coalesce((select auth.jwt()) -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
  );

create policy tgd_requests_admin_update
  on public.listing_requests
  for update
  to authenticated
  using (
    coalesce((select auth.jwt()) ->> 'role', '') in ('admin', 'service_role')
    or coalesce((select auth.jwt()) -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
  )
  with check (
    coalesce((select auth.jwt()) ->> 'role', '') in ('admin', 'service_role')
    or coalesce((select auth.jwt()) -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
  );

create policy tgd_requests_admin_delete
  on public.listing_requests
  for delete
  to authenticated
  using (
    coalesce((select auth.jwt()) ->> 'role', '') in ('admin', 'service_role')
    or coalesce((select auth.jwt()) -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
  );
